package cli

import (
	"fmt"
	"os"
)

// wrapperVersion is stamped into the generated function and checked on every
// invocation, so a shell still running an older eval'd function gets told to
// re-source instead of silently misbehaving. Bump it whenever the emitted
// shell code changes behavior.
const wrapperVersion = "10"

// The function is POSIX-compatible so one template serves zsh and bash; only
// the completion blocks below differ per shell.
// An unrecognized first word may be a user alias for a jump command — only
// the binary can know (aliases live in git config), so the wrapper asks it.
const shellFunction = `# wt — generated by "worktree init"
wt() {
    local _wt_bin=%q _wt_jump=""
    case "$1" in
        checkout|ch|create|fork|home|switch|peek|unpeek) _wt_jump=1 ;;
        root) case "$2" in checkout|ch|create|fork) _wt_jump=1 ;; esac ;;
        alias|base|complete|deps|help|init|link|list|ls|prompt|remove|reset|rm|status|version|--version|-h|--help|"") ;;
        *) [ "$("$_wt_bin" __jump-alias "$1" "$2" 2>/dev/null)" = 1 ] && _wt_jump=1 ;;
    esac
    if [ -n "$_wt_jump" ]; then
        local _wt_script
        _wt_script="$(WT_WRAPPER_VERSION=%s WT_PREV="${_wt_prev:-}" "$_wt_bin" "$@")" || return $?
        if [ -n "$_wt_script" ]; then
            _wt_prev="$PWD"
            eval "$_wt_script"
        fi
    else
        WT_WRAPPER_VERSION=%s "$_wt_bin" "$@"
    fi
}
`

// The completion functions stay dumb on purpose: they hand the binary the
// words typed before the cursor and list whatever comes back, so candidate
// logic lives in Go (see complete.go) and new commands complete without
// re-sourcing anything but the binary.
const zshCompletion = `
_wt() {
    local -a candidates
    local IFS=$'\n'
    candidates=($(%[1]q complete "${(@)words[2,CURRENT-1]}" 2>/dev/null))
    (( ${#candidates} )) || return 1
    _describe -t wt-candidates 'wt' candidates
}
if ! (( $+functions[compdef] )); then
    # completion system not initialized yet (eval ran before compinit)
    autoload -Uz compinit && compinit -C
fi
(( $+functions[compdef] )) && compdef _wt wt worktree
`

const bashCompletion = `
_wt_complete() {
    local cur=${COMP_WORDS[COMP_CWORD]} IFS=$'\n'
    local -a words=("${COMP_WORDS[@]:1:$((COMP_CWORD-1))}")
    local -a candidates=($(%[1]q complete "${words[@]}" 2>/dev/null))
    candidates=("${candidates[@]%%:*}")
    COMPREPLY=($(compgen -W "${candidates[*]}" -- "$cur"))
}
complete -F _wt_complete wt worktree
`

func shellInit(args []string) error {
	if len(args) != 1 || (args[0] != "zsh" && args[0] != "bash") {
		return fmt.Errorf("usage: wt init <zsh|bash>")
	}
	bin, err := os.Executable()
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, shellFunction, bin, wrapperVersion, wrapperVersion)
	switch args[0] {
	case "zsh":
		fmt.Fprintf(stdout, zshCompletion, bin)
	case "bash":
		fmt.Fprintf(stdout, bashCompletion, bin)
	}
	return nil
}
