package cli

import (
	"fmt"
	"os"
)

// wrapperVersion is stamped into the generated function and checked on every
// invocation, so a shell still running an older eval'd function gets told to
// re-source instead of silently misbehaving. Bump it whenever shellFunction
// changes behavior.
const wrapperVersion = "4"

// The function is POSIX-compatible so one template serves zsh and bash; the
// shell argument is kept for future per-shell completions.
const shellFunction = `# wt — generated by "worktree init"
wt() {
    local _wt_bin=%q
    case "$1" in
        checkout|ch|create|fork|home|switch)
            local _wt_dir
            _wt_dir="$(WT_WRAPPER_VERSION=%s WT_PREV="${_wt_prev:-}" "$_wt_bin" "$@")" || return $?
            if [ -n "$_wt_dir" ]; then
                _wt_prev="$PWD"
                cd "$_wt_dir"
            fi
            ;;
        *)
            WT_WRAPPER_VERSION=%s "$_wt_bin" "$@"
            ;;
    esac
}
`

func shellInit(args []string) error {
	if len(args) != 1 || (args[0] != "zsh" && args[0] != "bash") {
		return fmt.Errorf("usage: wt init <zsh|bash>")
	}
	bin, err := os.Executable()
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, shellFunction, bin, wrapperVersion, wrapperVersion)
	return nil
}
