package cli

import (
	"fmt"
	"os"
)

// wrapperVersion is stamped into the generated function and checked on every
// invocation, so a shell still running an older eval'd function gets told to
// re-source instead of silently misbehaving. Bump it whenever shellFunction
// changes behavior.
const wrapperVersion = "6"

// The function is POSIX-compatible so one template serves zsh and bash; the
// shell argument is kept for future per-shell completions.
const shellFunction = `# wt — generated by "worktree init"
wt() {
    local _wt_bin=%q _wt_jump=""
    case "$1" in
        checkout|ch|create|fork|home|switch) _wt_jump=1 ;;
        root) case "$2" in checkout|ch|create|fork) _wt_jump=1 ;; esac ;;
    esac
    if [ -n "$_wt_jump" ]; then
        local _wt_script
        _wt_script="$(WT_WRAPPER_VERSION=%s WT_PREV="${_wt_prev:-}" "$_wt_bin" "$@")" || return $?
        if [ -n "$_wt_script" ]; then
            _wt_prev="$PWD"
            eval "$_wt_script"
        fi
    else
        WT_WRAPPER_VERSION=%s "$_wt_bin" "$@"
    fi
}
`

func shellInit(args []string) error {
	if len(args) != 1 || (args[0] != "zsh" && args[0] != "bash") {
		return fmt.Errorf("usage: wt init <zsh|bash>")
	}
	bin, err := os.Executable()
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, shellFunction, bin, wrapperVersion, wrapperVersion)
	return nil
}
